version: "3.9"

networks:
  shared_dist_sys_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dist_sys_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_dist_sys_network

  logger:
    container_name: dist_sys_logger
    build: ./logger
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  booking:
    container_name: dist_sys_booking
    build: ./booking
    ports:
      - "1234:1234"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  itinerary:
    container_name: dist_sys_itinerary
    build: ./itinerary
    ports:
      - "1236:1236"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  payments:
    container_name: dist_sys_payments
    build: ./payments
    ports:
      - "1237:1237"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  payments_api:
    container_name: dist_sys_payments_api
    build: ./payments_api
    ports:
      - "1238:1238"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  tickets:
    container_name: dist_sys_tickets
    build: ./tickets
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  marketing:
    container_name: dist_sys_marketing
    build: ./marketing
    ports:
      - "1235:1235"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: dist_sys_frontend
  #   ports:
  #     - "5173:80"
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - shared_dist_sys_network
  #   restart: unless-stopped
