version: "3.9"

networks:
  shared_dist_sys_network:
    driver: bridge

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: dist_sys_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared_dist_sys_network

  logger:
    container_name: dist_sys_logger
    build: ./logger
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  reservation:
    container_name: dist_sys_reservation
    build: ./reservation
    ports:
      - "1234:1234"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  payments:
    container_name: dist_sys_payments
    build: ./payments
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  tickets:
    container_name: dist_sys_tickets
    build: ./tickets
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  promotions:
    container_name: dist_sys_promotions
    build: ./promotions
    ports:
      - "1235:1235"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - shared_dist_sys_network
    env_file:
      - .env
    restart: unless-stopped

  subscriber:
    container_name: dist_sys_subscriber
    build: ./subscriber
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - shared_dist_sys_network
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dist_sys_frontend
    ports:
      - "5173:80"
    depends_on:
      - rabbitmq
    networks:
      - shared_dist_sys_network
    restart: unless-stopped
